"""
train_sos_priority.py
=====================
Train a PyTorch MLP to classify SOS urgency (urgent_15m: 0 or 1).

Input dataset : data/sos_priority_dataset.csv  (generated by export_sos_dataset.py)
Output        : models/sos_priority_model.pt
                models/sos_priority_scaler.joblib

Features used (8):
  lat, lon, flood_prob_near, people_count, status_enc,
  hour_of_day, is_night, is_weekend

Label:
  urgent_15m — 1 nếu SOS được xử lý trong ≤ 15 phút

Chạy: python train_sos_priority.py
"""

import os
import sys
import numpy as np
import pandas as pd
import joblib
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, accuracy_score

# ─── CONFIG ───────────────────────────────────────────────────────────────────
BASE_DIR    = os.path.dirname(__file__)
DATA_PATH   = os.path.join(BASE_DIR, "data", "sos_priority_dataset.csv")
MODEL_DIR   = os.path.join(BASE_DIR, "models")
MODEL_PATH  = os.path.join(MODEL_DIR, "sos_priority_model.pt")
SCALER_PATH = os.path.join(MODEL_DIR, "sos_priority_scaler.joblib")

FEATURE_COLS = [
    "lat", "lon", "flood_prob_near", "people_count", "status_enc",
    "hour_of_day", "is_night", "is_weekend",
]
LABEL_COL    = "urgent_15m"

EPOCHS        = 150
BATCH_SIZE    = 32
LR            = 1e-3
EARLY_STOP    = 15      # epochs tanpa improvement sebelum stop
TEST_SIZE     = 0.20
RANDOM_SEED   = 42
# ──────────────────────────────────────────────────────────────────────────────


class SOSPriorityNet(nn.Module):
    """Lightweight MLP: 8 → 32 → 16 → 1 (sigmoid output)."""

    def __init__(self, n_features: int = 6):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_features, 32),
            nn.ReLU(),
            nn.Dropout(0.30),
            nn.Linear(32, 16),
            nn.ReLU(),
            nn.Linear(16, 1),
            nn.Sigmoid(),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x).squeeze(-1)


def load_data(path: str):
    if not os.path.exists(path):
        print(f"[ERROR] Không tìm thấy dataset: {path}")
        print("        Hãy chạy export_sos_dataset.py trước.")
        sys.exit(1)

    df = pd.read_csv(path)
    missing = [c for c in FEATURE_COLS + [LABEL_COL] if c not in df.columns]
    if missing:
        print(f"[ERROR] Thiếu cột trong dataset: {missing}")
        sys.exit(1)

    X = df[FEATURE_COLS].values.astype(np.float32)
    y = df[LABEL_COL].values.astype(np.float32)
    print(f"[INFO] Dataset: {len(df)} samples | features={FEATURE_COLS}")
    return X, y


def main():
    torch.manual_seed(RANDOM_SEED)
    np.random.seed(RANDOM_SEED)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"[INFO] Device: {device}")

    # ── Load & Split ──────────────────────────────────────────────────────────
    X, y = load_data(DATA_PATH)

    n_pos = int(y.sum())
    n_neg = len(y) - n_pos
    print(f"[INFO] Label distribution — urgent=1: {n_pos}, normal=0: {n_neg}")

    if len(y) < 10:
        print("[WARN] Quá ít dữ liệu (< 10 bản ghi). Model sẽ không hội tụ tốt.")

    # Stratified split giữ tỉ lệ label.
    try:
        X_train, X_val, y_train, y_val = train_test_split(
            X, y, test_size=TEST_SIZE, random_state=RANDOM_SEED, stratify=y
        )
    except ValueError:
        # Nếu class quá ít không stratify được.
        X_train, X_val, y_train, y_val = train_test_split(
            X, y, test_size=TEST_SIZE, random_state=RANDOM_SEED
        )

    # ── Scaler ────────────────────────────────────────────────────────────────
    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_val   = scaler.transform(X_val)

    # ── Tensors & DataLoaders ─────────────────────────────────────────────────
    def to_tensor_ds(X_arr, y_arr):
        return TensorDataset(
            torch.tensor(X_arr, dtype=torch.float32),
            torch.tensor(y_arr, dtype=torch.float32),
        )

    train_ds = to_tensor_ds(X_train, y_train)
    val_ds   = to_tensor_ds(X_val,   y_val)

    train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True)
    val_loader   = DataLoader(val_ds,   batch_size=BATCH_SIZE, shuffle=False)

    # ── Model / Loss / Optimizer ──────────────────────────────────────────────
    model     = SOSPriorityNet(n_features=len(FEATURE_COLS)).to(device)
    # BCELoss khi dùng với Sigmoid output; thay BCEWithLogits nếu bỏ Sigmoid.
    criterion = nn.BCELoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=LR)
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, mode="min", factor=0.5, patience=7
    )

    # ── Training loop ─────────────────────────────────────────────────────────
    best_val_loss = float("inf")
    best_state    = None
    no_impr       = 0

    print(f"\n{'Epoch':>6} | {'Train Loss':>10} | {'Val Loss':>8} | {'Val Acc':>7} | {'Val AUC':>7}")
    print("-" * 55)

    for epoch in range(1, EPOCHS + 1):
        # ── Train ──
        model.train()
        train_losses = []
        for Xb, yb in train_loader:
            Xb, yb = Xb.to(device), yb.to(device)
            optimizer.zero_grad()
            preds = model(Xb)
            loss  = criterion(preds, yb)
            loss.backward()
            optimizer.step()
            train_losses.append(loss.item())

        # ── Validate ──
        model.eval()
        val_losses, val_preds_list, val_true_list = [], [], []
        with torch.no_grad():
            for Xb, yb in val_loader:
                Xb, yb = Xb.to(device), yb.to(device)
                preds       = model(Xb)
                loss        = criterion(preds, yb)
                val_losses.append(loss.item())
                val_preds_list.extend(preds.cpu().numpy().tolist())
                val_true_list.extend(yb.cpu().numpy().tolist())

        train_loss = float(np.mean(train_losses))
        val_loss   = float(np.mean(val_losses))

        val_pred_labels = [1 if p >= 0.5 else 0 for p in val_preds_list]
        val_acc  = accuracy_score(val_true_list, val_pred_labels)
        try:
            val_auc = roc_auc_score(val_true_list, val_preds_list)
        except ValueError:
            val_auc = float("nan")  # Chỉ có 1 class trong val set

        scheduler.step(val_loss)

        if epoch % 10 == 0 or epoch == 1:
            print(f"{epoch:>6} | {train_loss:>10.4f} | {val_loss:>8.4f} | "
                  f"{val_acc:>7.4f} | {val_auc:>7.4f}")

        # ── Early stop ──
        if val_loss < best_val_loss - 1e-5:
            best_val_loss = val_loss
            best_state    = {k: v.clone() for k, v in model.state_dict().items()}
            no_impr       = 0
        else:
            no_impr += 1
            if no_impr >= EARLY_STOP:
                print(f"\n[INFO] Early stop tại epoch {epoch} (không cải thiện {EARLY_STOP} epoch).")
                break

    # ── Restore best & final evaluation ──────────────────────────────────────
    if best_state:
        model.load_state_dict(best_state)

    model.eval()
    all_preds, all_true = [], []
    with torch.no_grad():
        for Xb, yb in val_loader:
            Xb = Xb.to(device)
            p  = model(Xb).cpu().numpy()
            all_preds.extend(p.tolist())
            all_true.extend(yb.numpy().tolist())

    final_labels = [1 if p >= 0.5 else 0 for p in all_preds]
    final_acc    = accuracy_score(all_true, final_labels)
    try:
        final_auc = roc_auc_score(all_true, all_preds)
    except ValueError:
        final_auc = float("nan")

    print("\n" + "=" * 55)
    print(f"[RESULT] Best Val Loss : {best_val_loss:.4f}")
    print(f"[RESULT] Final Val Acc : {final_acc:.4f}")
    print(f"[RESULT] Final Val AUC : {final_auc:.4f}")
    print("=" * 55)

    # ── Save ─────────────────────────────────────────────────────────────────
    os.makedirs(MODEL_DIR, exist_ok=True)

    # Lưu model weights + metadata (feature list, threshold).
    torch.save({
        "model_state": model.state_dict(),
        "feature_cols": FEATURE_COLS,
        "n_features": len(FEATURE_COLS),
        "threshold": 0.5,
        "val_acc": final_acc,
        "val_auc": final_auc,
    }, MODEL_PATH)

    joblib.dump(scaler, SCALER_PATH)

    print(f"\n[OK] Model lưu tại  : {MODEL_PATH}")
    print(f"[OK] Scaler lưu tại : {SCALER_PATH}")


if __name__ == "__main__":
    main()
